FROM python:3.11-alpine
ARG APP_DIR=/src

RUN apk --no-cache add curl build-base libffi-dev

ENV POETRY_VERSION=2.1.4
RUN curl -sSL https://install.python-poetry.org | python3 -
ENV PATH /root/.local/bin:$PATH

WORKDIR ${APP_DIR}

COPY pyproject.toml poetry.lock ./

RUN poetry install --no-root
COPY . ./

RUN apk --no-cache add bash

CMD poetry run python -m src.main
